### ISSUE TITLE
delete repo

### ISSUE THREAD

**Issue by virtualex-itv** [kengibous/openlens-choco#1]
hey - feel free to delete this repo as the package has been converted to AU and is in our repo.  Also, there was an error in your installation script.  Looks like you hijacked my old/other package code but forgot to modify one of the silent params.  Revision has already been pushed and awaiting moderation.

You can delete this repository.

Thanks.
virtualex
chocolatey team

**Comment by kengibous** [comment]
@virtualex-itv sure I will delete this - however using the term “hijacked” is a bit hostile, especially for open source things.
